addons:
  code_climate:
    repo_token: 46fe7f79f112a6e86be905944c6384365ad67172ae27b84141b93b2c8d5f4ea0

after_success:
  - bundle exec codeclimate-test-reporter

gemfile:
  - gemfiles/latest.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile

jobs:
  include:
    - stage: RSpec
      script: bundle exec rspec
    - stage: RuboCop
      script: bundle exec rubocop

language: ruby

rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0

services:
  - redis-server
